### ISSUE TITLE
Add New Driver

### ISSUE THREAD

**Issue by neon-lab-dev** [neon-lab-dev/product-service#14]
## Requirement

- [x] create driver table in the database. This entity will be created in product-service. 
- [x] add driver entity.
- [x] POST request
- [x] Driver
     -  name 
     -  contantNo
     - vehicle no
     - generic () 

Linked to : #1

**Comment by shrawanindeshpande** [comment]
1. created driver entity
2. created controller, service, and repository layer for the same

no problems faced so far

**Comment by neon-lab-dev** [comment]
@shrawanindeshpande Thanks for the update. I hope can you please raise PR from your branch to the master. Let it be incomplete. I just want to see the changes and progress as of now.

cc- @smackdowna

**Comment by shrawanindeshpande** [comment]
today i am working on add driver API no doubts do far

**Comment by shrawanindeshpande** [comment]
1. created request and response DTOs
2. written function to add driver in the service layer
no problems faced so far

**Comment by shrawanindeshpande** [comment]
completed add driver api
