### ISSUE TITLE
Creating DLD for all the product flows

### ISSUE THREAD

**Issue by neon-lab-dev** [neon-lab-dev/product-service#2]
This ticket is linked to the ticket #1 .

For all the product flows _flowchart_ needs to be prepared

**Comment by ritik-agrawal** [comment]
## Question

### Context
Avoiding duplicate products while adding product flow.

### Problem 
In the current schema (as mentioned in the document in this [link](https://github.com/neon-lab-dev/product-service/issues/1#issuecomment-2029165987), we do not have any unique identifier that can help in distinguishing if the current product is new of old.

### Solution

- We need to expose searchBy<column>API where <column> can be ,
     - product.name
     - product.code
- The user should be able to select from the drop-down.
- The drop-down should be visible post _the pre-defined length of characters_ has been entered in the text box
- When selected from the drop-down rest of the fields should be auto-populated

#### Note
the no of pieces entered will be added to the existing stock count. 

In the database, we have 10 Milky Moo pieces. If in the add-product screen, a user selects Milky Moo and enters pieces as 5. Now, the total number of entries will be 15.

cc- @smackdowna

**Comment by neon-lab-dev** [comment]
@smackdowna can we have all possible units that need to be in the system.

**Comment by neon-lab-dev** [comment]
Task:
- Understanding the diagrams related to the product
- Explore preliminary on how to run docker-compose file
- Tech stack to use
   -  java 17
   - mysql
   - gradle 8

cc- @sjha24 @smackdowna

**Comment by neon-lab-dev** [comment]
As discussed with @sjha24 , below are the pending points,
- Migration from maven to gradle
- creation of `updateProductApi` diagram

We will address the docker issue post the above pending points are resolved.

cc- @smackdowna

**Comment by neon-lab-dev** [comment]
## update
- Documentation for the crud operation for the product is completed. 
- Code setup done with @sjha24 . 
- @sjha24 need to complete the ADD product API by tomorrow morning.

cc- @smackdowna @ritik-agrawal

**Comment by neon-lab-dev** [comment]
## Update
- Completed one round of code review with @sjha24 and asked to do some changes
- As per the code status, the `addProductApi` is working fine (Without document upload part)
- This is expected to be done by tomorrow mid day. (Without document upload part)
- I have implemented the `role-based access` for login service today
- I will start working on the `uploadDocumentApi` tomorrow and it is expected to be available by 2024/04/11.


cc- @smackdowna

**Comment by neon-lab-dev** [comment]
## Updates
- Completed 2nd round of code review with @sjha24 on product add API.
- The changes are expected. A few more minor changes has been added. 
- The Add product API will be done today.
- @sjha24 will be starting `deleteProductApi` today.

cc- @smackdowna

**Comment by neon-lab-dev** [comment]
## Updates
- Completed one round of code review with @sjha24 . 
- I have clarified some of the miscommunications related to the review comments
- `DeleteProductApi` will be done today mid day.
- Today @sjha24 will start `updateProdcutApi` 

cc- @smackdowna

**Comment by neon-lab-dev** [comment]
## Updates

- Completed one round of code review with @sjha24 .
- Suggested few changes in the code.
- After this he will be working on modifying the `deleteProdcutApi` to delete the whole product as discussed with @smackdowna .
- I will be working on the `uploadDocumentApi` on Saturday.

cc- @smackdowna

**Comment by neon-lab-dev** [comment]
## Diagrams

- addProductApi: https://whimsical.com/add-product-api-MtNTyWXcoJwTT4rhuAnwqZ
- updateProductApi: https://whimsical.com/update-product-api-SH5HpT68oY3ryCRESC9eyz
- deleteProductApi: https://whimsical.com/delete-product-api-J6NdgH8ejLKmaHjJ8hNbQR
- uploadDocumentApi: https://whimsical.com/uploaddocumentapi-SH8trDxu9ddEuHrbLiGMYw

cc- @smackdowna @sjha24

**Comment by neon-lab-dev** [comment]
closing the ticket.
