### ISSUE TITLE
Document service provider integration

### ISSUE THREAD

**Issue by neon-lab-dev** [neon-lab-dev/product-service#39]
# Problem

Currently the images are being stored in the database. To scale up, we will be integrating as service provider to the system

# Service Provider

link: https://imagekit.io/plans/ 

Linked to #1

**Comment by neon-lab-dev** [comment]
@sjha24 please start going through the documentation in the above link. This will help in the integration of the same in our application.

**Comment by ritik-agrawal** [comment]
The changes has been successfully deployed to aws now.
