### ISSUE TITLE
Product list bugs

### ISSUE THREAD

**Issue by neon-lab-dev** [neon-lab-dev/product-service#46]
# Problem

- [x] currently the fetch API does not support search by quantity. This is required for out of stock products filteration. 
- [x] Total count of current queryable object

**Comment by ritik-agrawal** [comment]
Initial changes done for the ticket. I will close the ticket post confirmation from Tilak Tahpa.

**Comment by ritik-agrawal** [comment]
Had an discusstion with Tilak. In the product report. I need to send the total in stock products as well.

**Comment by ritik-agrawal** [comment]
This issue has been resolved.
